export default [
  "You don't need tests.",
  'When in doubt, use a popup.',
  'Let’s debug it directly in production.',
  'Just ship it already.',
  'The leak is minor, we’ll just add more RAM later.',
  'Looks like it’s all working fine.',
  'We’ll fix it later.',
  'This new requirement is an easy one, just a couple of "ifs".',
  'Does it support blockchain?',
  "Didn't we refactor last year?",
  'Technical debt? Never heard of it.',
  'Writing tests takes x3 time than writing actual code.',
  'We need you to work on features. Not performance.',
  'Please do not worry a lot about quality. This is a prototype.',
  'Can we worry about security later?',
];
