export default [
  "You don't need tests.",
  'When in doubt, use a popup.',
  "Let's debug it directly in production.",
  'Just ship it already.',
  "The memory leak is insignificant - we'll add more RAM later.",
  "Looks like it's all working fine.",
  "We'll fix it later.",
  'This new requirement is an easy one, just a couple of "ifs".',
  'Does it support blockchain?',
  "Didn't we refactor last year?",
  'Technical debt? Never heard of it.',
  'Writing tests takes x3 time than writing actual code.',
  'We need you to work on features, not performance.',
  'Please do not worry a lot about quality. This is a prototype.',
  "It's too early to think about security.",
  'You can find all the AWS passwords posted on the fridge.',
  'Can you redesign this? Our website should look more like LinkedIn.',
  'No need to focus on UX. We will make a video with instructions.',
  'We are not that big, this will never happen to us.',
  "It's NoSQL. It scales well.",
  'This is a corner case that will never occur in production.',
  "If it works don't touch it.",
  'The data is safe. We run RAID 6.',
  'Client said we need a quick and dirty solution.',
  'Go ahead. This will only incur a 10 seconds downtime.',
  'Amazon EC2 has zero downtime, so there is no need to setup a standby server.',
  'Last time I checked, the backup was working fine.',
  "There is no time to update the application. We'll solve this using a stored procedure.",
  'There is no need for an index; this table will never grow large.',
  'Can you give me 5 minutes for a last CSS fix before the production deployment?',
  "Please train those 3 new people we've hired. They will help you with your late project.",
  'The application has zero bugs.',
  "We don't have an analyst. Analysis will be done by all of us!",
  'No need for a pentest because we will run this on the cloud.',
  "We've been doing it like this for years.",
];
